version: '3'
networks:
  default:
    external:
      name: compose_container_services_networks
services:

  quantal_email_service:
    build:
      context: ./../../
      dockerfile: ./docker/Dockerfile
    ports:
      - ${WEB_APP_PORT:-9100}:3000
    environment:
      - DB_HOST=quantal_email_service_db
      - DB_NAME=quantal_email_service_db
      - DB_PORT=5432
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
      - USE_MAILGUN_IN_TEST_MODE=true
      - NODE_ENV
    links:
      - quantal_email_service_db
    depends_on:
      - quantal_email_service_db
    command: ["/wait-for-it.sh", "-t", "30", "quantal_email_service_db:5432", "--","npm","--prefix", "/opt/app/", "start"]
    volumes:
      - /private/var/docker/log/quantal_email_service:/var/log

  # The postgres database
  quantal_email_service_db:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - ${DB_PORT_EXPOSED_ON_HOST:-5437}:5432
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=quantal_email_service_db
      - PG_PASSWORD=postgres
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

    volumes:
      - /private/var/docker/postgresql/quantal_email_service_db:/var/lib/postgresql
