version: '2'
networks:
  default:
    external:
      name: compose_container_services_networks
services:

  quantal_email_service:
    build:
      context: ./../../
      dockerfile: ./docker/Dockerfile
    ports:
      - "9100:3000"
      - "5015:5015"
    environment:
      - DB_HOST=quantal_email_service_db
      - DB_NAME=quantal_email_service_db
      - DB_PORT=5432
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - JWT_TYPE=${JWT_TYPE}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - API_GATEWAY_ENDPOINT=${API_GATEWAY_ENDPOINT}
    links:
      - quantal_email_service_db
    depends_on:
      - quantal_email_service_db
    command: ["/wait-for-it.sh", "quantal_email_service_db:5432", "--","npm","--prefix", "/opt/app/", "start"]
    volumes:
      - /private/var/docker/log/quantal_email_service:/var/log

    #networks:
     # - container_services_networks

  # The postgres database
  quantal_email_service_db:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5437:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=quantal_email_service_db
      - PG_PASSWORD=postgres
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

    volumes:
      - /private/var/docker/postgresql/quantal_email_service_db:/var/lib/postgresql
